PREFIX rdfh: <http://lod2.eu/schemas/rdfh#>
SELECT (SUM(?lo_extendedprice * ?lo_discount) AS ?sum_revenue)
WHERE {
	?li a rdfh:lineorder ;
	   rdfh:lo_orderdate ?lo_orderdate ;
	   rdfh:lo_extendedprice ?lo_extendedprice ;
	   rdfh:lo_discount ?lo_discount ;
	   rdfh:lo_quantity ?lo_quantity .
	?lo_orderdate rdfh:d_year ?d_year .
	?lo_orderdate rdfh:d_month ?d_month .

	FILTER(?d_year = 1993 && ?d_month = 'January')
	FILTER((?lo_discount >= 1) && (?lo_discount <= 3) && (?lo_quantity < 25)) 
}