PREFIX : <http://example.com/>
SELECT (SUM(?lo_extendedprice * ?lo_discount) AS ?sum_revenue)
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :extendedprice ?lo_extendedprice ;
	   :discount ?lo_discount ;
	   :quantity ?lo_quantity .
	?lo_orderdate :year ?year .
	?lo_orderdate :month ?month .

	FILTER(?year = 1993 && ?month = 'January')
	FILTER((?lo_discount >= 1) && (?lo_discount <= 3) && (?lo_quantity < 25)) 
}