PREFIX : <http://example.com/>
SELECT ?year ?s_city ?p_brand1 (SUM(?lo_revenue - ?lo_supplycost) AS ?sum_profit) 
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :custkey ?lo_custkey ;
	   :partkey ?lo_partkey ;
	   :suppkey ?lo_suppkey ;
	   :revenue ?lo_revenue ;
	   :supplycost ?lo_supplycost .

	?lo_suppkey :city ?s_city .
	?lo_suppkey :nation 'UNITED STATES'@en .
	?lo_partkey :category 'MFGR#14'@en .  
	?lo_partkey :brand ?p_brand1 .
	?lo_orderdate :year ?year .
	FILTER(?year = 1997 || ?year = 1998)
}
GROUP BY ?year ?s_city ?p_brand1 
ORDER BY ?year ?s_city ?p_brand1