PREFIX : <http://example.com/>
SELECT (SUM(?_lo_revenue) AS ?lo_revenue) ?year ?p_brand1 
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :partkey ?lo_partkey ;
	   :suppkey ?lo_suppkey ;
	   :revenue ?_lo_revenue .

	?lo_partkey :brand ?p_brand1 .
	?lo_partkey :category 'MFGR#12' .
	?lo_suppkey :region 'AMERICA' . 
	?lo_orderdate :year ?year .
}
GROUP BY ?year ?p_brand1 
ORDER BY ?year ?p_brand1