PREFIX : <http://example.com/>
SELECT (SUM(?extendedprice * ?discount) AS ?sum_revenue)
WHERE {
	?li :orderdate ?orderdate ;
	   :extendedprice ?extendedprice ;
	   :discount ?discount ;
	   :quantity ?quantity .
	?orderdate :yeamonthnum ?yearmonth .

	FILTER(?yearmonth = 199401)
	FILTER((?discount >= 1) && (?discount <= 3) && (?quantity < 25)) 
}