PREFIX : <http://example.com/>
SELECT (SUM(?lo_extendedprice * ?lo_discount) AS ?sum_revenue)
WHERE {
	?li :orderdate ?lo_orderdate ;
		:extendedprice ?lo_extendedprice ;
		:discount ?lo_discount ;
		:quantity ?lo_quantity .
	?lo_orderdate :weeknuminyear ?weeknuminyear .
	?lo_orderdate :year ?year .

	FILTER(?weeknuminyear = 6 && ?year = 1994)
	FILTER((?lo_discount >= 5) && (?lo_discount <= 7) && (?lo_quantity >= 26) && (?lo_quantity <= 35)) 
}