PREFIX rdfh: <http://lod2.eu/schemas/rdfh#>
SELECT (SUM(?rdfh_lo_revenue) AS ?lo_revenue) ?d_year ?p_brand1 
WHERE {
	?li a rdfh:lineorder ;
	   rdfh:lo_orderdate ?lo_orderdate ;
	   rdfh:lo_partkey ?lo_partkey ;
	   rdfh:lo_suppkey ?lo_suppkey ;
	   rdfh:lo_revenue ?rdfh_lo_revenue .

	?lo_partkey rdfh:p_brand1 ?p_brand1 .
	?lo_partkey rdfh:p_category 'MFGR#12' .
	?lo_suppkey rdfh:s_region 'AMERICA' . 
	?lo_orderdate rdfh:d_year ?d_year .
}
GROUP BY ?d_year ?p_brand1 
ORDER BY ?d_year ?p_brand1