PREFIX : <http://example.com/>
SELECT ?c_city ?s_city ?year (SUM(?_lo_revenue) AS ?lo_revenue)
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :custkey ?lo_custkey ;
	   :suppkey ?lo_suppkey ;
	   :revenue ?_lo_revenue .
	?lo_custkey :city ?c_city .
	?lo_suppkey :city ?s_city . 
	?lo_orderdate :year ?year .
	?lo_orderdate :yearmonth ?yearmonth .

	FILTER(?yearmonth = 'Dec1997')
	FILTER((?c_city='UNITED KI1' || ?c_city='UNITED KI5') && (?s_city='UNITED KI1' || ?s_city='UNITED KI5'))
}
GROUP BY ?c_city ?s_city ?year 
ORDER BY ASC(?year) DESC(?lo_revenue) 