PREFIX rdfh: <http://lod2.eu/schemas/rdfh#>
SELECT  ?c_nation ?s_nation ?d_year (SUM(?rdfh_lo_revenue) AS ?lo_revenue) 
WHERE {
	?li a rdfh:lineorder ;
	   rdfh:lo_orderdate ?lo_orderdate ;
	   rdfh:lo_custkey ?lo_custkey ;
	   rdfh:lo_suppkey ?lo_suppkey ;
	   rdfh:lo_revenue ?rdfh_lo_revenue .

	?lo_custkey rdfh:c_nation ?c_nation .
	?lo_custkey rdfh:c_region ?c_region .
	?lo_suppkey rdfh:s_nation ?s_nation .
	?lo_suppkey rdfh:s_region ?s_region . 
	?lo_orderdate rdfh:d_year ?d_year .
	FILTER(?c_region = 'ASIA')
	FILTER(?s_region = 'ASIA')
	FILTER(?d_year >= 1992 && ?d_year <= 1997)
}
GROUP BY ?c_nation ?s_nation ?d_year 
ORDER BY ASC(?d_year) DESC(?lo_revenue)