PREFIX : <http://example.com/>
SELECT  ?c_nation ?s_nation ?year (SUM(?_lo_revenue) AS ?lo_revenue) 
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :custkey ?lo_custkey ;
	   :suppkey ?lo_suppkey ;
	   :revenue ?_lo_revenue .

	?lo_custkey :nation ?c_nation .
	?lo_custkey :region ?c_region .
	?lo_suppkey :nation ?s_nation .
	?lo_suppkey :region ?s_region . 
	?lo_orderdate :year ?year .
	FILTER(?c_region = 'ASIA'@en)
	FILTER(?s_region = 'ASIA'@en)
	FILTER(?year >= 1992 && ?year <= 1997)
}
GROUP BY ?c_nation ?s_nation ?year 
ORDER BY ASC(?year) DESC(?lo_revenue)