PREFIX : <http://example.com/>
SELECT ?year ?c_nation (SUM(?lo_revenue - ?lo_supplycost) AS ?sum_profit) 
WHERE {
	?li :orderdate ?lo_orderdate ;
	   :custkey ?lo_custkey ;
	   :suppkey ?lo_suppkey ;
	   :revenue ?lo_revenue ;
	   :partkey ?lo_partkey ;
	   :supplycost ?lo_supplycost .

	?lo_custkey :region 'AMERICA'@en .
	?lo_suppkey :region 'AMERICA'@en .
	?lo_custkey :nation ?c_nation .
	?lo_partkey :mfgr ?p_mfgr . 
	?lo_orderdate :year ?year .
	FILTER(?year = 1992)
	FILTER((?p_mfgr = 'MFGR#1'@en || ?p_mfgr = 'MFGR#2'@en)).
}
GROUP BY ?year ?c_nation 
ORDER BY ?year ?c_nation