PREFIX : <http://example.com/>
SELECT (SUM(?_revenue) AS ?revenue) ?year ?p_brand1 
WHERE {
	?li :orderdate ?orderdate ;
	   :partkey ?partkey ;
	   :suppkey ?suppkey ;
	   :revenue ?_revenue .

	?partkey :brand ?p_brand1 .
	?partkey :category 'MFGR#12'@en .
	?suppkey :region 'AMERICA'@en . 
	?orderdate :year ?year .
}
GROUP BY ?year ?p_brand1 
ORDER BY ?year ?p_brand1